general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font" }
bold = { family = "CaskaydiaMono Nerd Font" }
italic = { family = "CaskaydiaMono Nerd Font" }
size = 8

[window]
padding.x = 14
padding.y = 14

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]