general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font" }
bold = { family = "CaskaydiaMono Nerd Font" }
italic = { family = "CaskaydiaMono Nerd Font" }
size = 14

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[terminal.shell]
program = "powershell.exe"
args = [
    "-NoExit",
    "-ExecutionPolicy", "Bypass",
    "-Command", 
    "Import-Module 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\Tools\\Microsoft.VisualStudio.DevShell.dll'; Enter-VsDevShell -VsInstanceId 2af9171f -DevCmdArguments '-arch=x64'"
]

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
{ key = "F", mods = "Control|Shift", action = "ReceiveChar" },
{ key = "N", mods = "Control|Shift", action = "ReceiveChar" },
]
